window.ENEMY_REGISTRY = [
  { nombre: "Aarakocra Aeromante", xp_unidad: 1100 },
  { nombre: "Aarakocra Escaramuzador", xp_unidad: 50 },
  { nombre: "Cultista Aberrante", xp_unidad: 3900 },
  { nombre: "Aboleth", xp_unidad: 5900 },
  { nombre: "Yeti Abominable", xp_unidad: 5000 },
  { nombre: "Dragón Negro Adulto", xp_unidad: 11500 },
  { nombre: "Dragón Azul Adulto", xp_unidad: 15000 },
  { nombre: "Dragón de Latón Adulto", xp_unidad: 10000 },
  { nombre: "Dragón de Bronce Adulto", xp_unidad: 13000 },
  { nombre: "Dragón de Cobre Adulto", xp_unidad: 11500 },
  { nombre: "Dragón Profundo Adulto", xp_unidad: 7200 },
  { nombre: "Dragón Dorado Adulto", xp_unidad: 18000 },
  { nombre: "Dragón Verde Adulto", xp_unidad: 13000 },
  { nombre: "Dragón Rojo Adulto", xp_unidad: 18000 },
  { nombre: "Dragón Plateado Adulto", xp_unidad: 15000 },
  { nombre: "Dragón Espiritual Adulto", xp_unidad: 13000 },
  { nombre: "Dragón Blanco Adulto", xp_unidad: 10000 },
  { nombre: "Elemental de Aire", xp_unidad: 1800 },
  { nombre: "Alosaurio", xp_unidad: 450 },
  { nombre: "Señor de Animales", xp_unidad: 25000 },
  { nombre: "Armadura Animada", xp_unidad: 200 },
  { nombre: "Escoba Encantada", xp_unidad: 50 },
  { nombre: "Espada Voladora Animada", xp_unidad: 50 },
  { nombre: "Alfombra Asfixiante Animada", xp_unidad: 450 },
  { nombre: "Ankheg", xp_unidad: 450 },
  { nombre: "Anquilosaurio", xp_unidad: 700 },
  { nombre: "Simio", xp_unidad: 100 },
  { nombre: "Araña Feérica", xp_unidad: 450 },
  { nombre: "Arcanaloto", xp_unidad: 8400 },
  { nombre: "Bruja Mayor", xp_unidad: 33000 },
  { nombre: "Archelon", xp_unidad: 1100 },
  { nombre: "Archimago", xp_unidad: 8000 },
  { nombre: "Arzobispo", xp_unidad: 8400 },
  { nombre: "Asesino", xp_unidad: 3900 },
  { nombre: "Arbusto Despertado", xp_unidad: 10 },
  { nombre: "Árbol Despertado", xp_unidad: 450 },
  { nombre: "Pico de Hacha", xp_unidad: 50 },
  { nombre: "Azer Piro-mago", xp_unidad: 2300 },
  { nombre: "Azer Centinela", xp_unidad: 450 },
  { nombre: "Babuino", xp_unidad: 10 },
  { nombre: "Tejón", xp_unidad: 10 },
  { nombre: "Bálor", xp_unidad: 22000 },
  { nombre: "Bandido", xp_unidad: 25 },
  { nombre: "Capitán Bandido", xp_unidad: 450 },
  { nombre: "Señor del Crimen Bandido", xp_unidad: 7200 },
  { nombre: "Bandido Engañador", xp_unidad: 2900 },
  { nombre: "Banshee", xp_unidad: 1100 },
  { nombre: "Demonio de Espinas", xp_unidad: 1800 },
  { nombre: "Barlgura", xp_unidad: 1800 },
  { nombre: "Basilisco", xp_unidad: 700 },
  { nombre: "Murciélago", xp_unidad: 10 },
  { nombre: "Demonio Barbudo", xp_unidad: 700 },
  { nombre: "Bestia de Malar", xp_unidad: 7200 },
  { nombre: "Behir", xp_unidad: 7200 },
  { nombre: "Mirador", xp_unidad: 10000 },
  { nombre: "Mirador Zombi", xp_unidad: 1800 },
  { nombre: "Berserker", xp_unidad: 450 },
  { nombre: "Comandante Berserker", xp_unidad: 3900 },
  { nombre: "Biha Babir", xp_unidad: 8400 },
  { nombre: "Oso Negro", xp_unidad: 100 },
  { nombre: "Cría de Dragón Negro", xp_unidad: 450 },
  { nombre: "Minga Negra", xp_unidad: 1100 },
  { nombre: "Perro Relámpago", xp_unidad: 50 },
  { nombre: "Blob de Aniquilación", xp_unidad: 50000 },
  { nombre: "Cría de Dragón Azul", xp_unidad: 700 },
  { nombre: "Slaad Azul", xp_unidad: 2900 },
  { nombre: "Jabalí", xp_unidad: 50 },
  { nombre: "Demonio de Huesos", xp_unidad: 5000 },
  { nombre: "Naga de Huesos", xp_unidad: 1100 },
  { nombre: "Contrabandista Boromar", xp_unidad: 100 },
  { nombre: "Subjefe Boromar", xp_unidad: 3900 },
  { nombre: "Cría de Dragón de Latón", xp_unidad: 200 },
  { nombre: "Gorgona de Bronce", xp_unidad: 5000 },
  { nombre: "Cría de Dragón de Bronce", xp_unidad: 450 },
  { nombre: "Oso Pardo", xp_unidad: 200 },
  { nombre: "Bugbear Acechador", xp_unidad: 700 },
  { nombre: "Bugbear Guerrero", xp_unidad: 200 },
  { nombre: "Bulette", xp_unidad: 1800 },
  { nombre: "Bulette Cachorro", xp_unidad: 450 },
  { nombre: "Bullywug Sabio del Pantano", xp_unidad: 1100 },
  { nombre: "Bullywug Guerrero", xp_unidad: 50 },
  { nombre: "Caldron Magen", xp_unidad: 1100 },
  { nombre: "Cambión", xp_unidad: 1800 },
  { nombre: "Camello", xp_unidad: 25 },
  { nombre: "Artesano Cannith", xp_unidad: 1100 },
  { nombre: "Rastreador de Carroña", xp_unidad: 450 },
  { nombre: "Gato", xp_unidad: 10 },
  { nombre: "Centauro Soldado", xp_unidad: 450 },
  { nombre: "Centauro Guardián", xp_unidad: 2900 },
  { nombre: "Demonio de Cadena", xp_unidad: 3900 },
  { nombre: "Chasme", xp_unidad: 2300 },
  { nombre: "Quimera", xp_unidad: 2300 },
  { nombre: "Chuul", xp_unidad: 1100 },
  { nombre: "Gólem de Arcilla", xp_unidad: 5000 },
  { nombre: "Capa Viviente", xp_unidad: 3900 },
  { nombre: "Gigante de las Nubes", xp_unidad: 5000 },
  { nombre: "Cocatriz", xp_unidad: 100 },
  { nombre: "Cocatriz Regente", xp_unidad: 3900 },
  { nombre: "Coloso", xp_unidad: 75000 },
  { nombre: "Común", xp_unidad: 10 },
  { nombre: "Serpiente Estranguladora", xp_unidad: 50 },
  { nombre: "Cría de Dragón de Cobre", xp_unidad: 200 },
  { nombre: "Rata Corrupta", xp_unidad: 10 },
  { nombre: "Couatl", xp_unidad: 1100 },
  { nombre: "Cangrejo", xp_unidad: 10 },
  { nombre: "Garra Caminante", xp_unidad: 10 },
  { nombre: "Cocodrilo", xp_unidad: 100 },
  { nombre: "Cultista", xp_unidad: 25 },
  { nombre: "Cultista Fanático", xp_unidad: 450 },
  { nombre: "Cultista Alto Sacerdote", xp_unidad: 5900 },
  { nombre: "Cultista de Demogorgon", xp_unidad: 25 },
  { nombre: "Cultistas", xp_unidad: 5000 },
  { nombre: "Cultistas de Bhaal", xp_unidad: 2900 },
  { nombre: "Cultistas de Myrkul", xp_unidad: 7200 },
  { nombre: "Ciclope Oráculo", xp_unidad: 5900 },
  { nombre: "Ciclope Centinela", xp_unidad: 2300 },
  { nombre: "Daask Matón", xp_unidad: 7200 },
  { nombre: "Daask Raider", xp_unidad: 200 },
  { nombre: "Dao", xp_unidad: 7200 },
  { nombre: "Dardew", xp_unidad: 1800 },
  { nombre: "Capa Oscura", xp_unidad: 100 },
  { nombre: "Escogido de los Tres Muertos", xp_unidad: 15000 },
  { nombre: "Cultista de la Muerte", xp_unidad: 3900 },
  { nombre: "Perro de la Muerte", xp_unidad: 200 },
  { nombre: "Caballero de la Muerte", xp_unidad: 18000 },
  { nombre: "Caballero de la Muerte Aspirante", xp_unidad: 7200 },
  { nombre: "Slaad de la Muerte", xp_unidad: 5900 },
  { nombre: "Tirano de la Muerte", xp_unidad: 11500 },
  { nombre: "Cría de Dragón Profundo", xp_unidad: 200 },
  { nombre: "Ciervo", xp_unidad: 10 },
  { nombre: "Demiliquia", xp_unidad: 20000 },
  { nombre: "Demobat", xp_unidad: 100 },
  { nombre: "Demodog", xp_unidad: 200 },
  { nombre: "Demodragón", xp_unidad: 1800 },
  { nombre: "Engendro de Demogorgon", xp_unidad: 450 },
  { nombre: "Deva", xp_unidad: 5900 },
  { nombre: "Lobo Enjuto", xp_unidad: 200 },
  { nombre: "Worg Enjuto", xp_unidad: 5900 },
  { nombre: "Bestia de Reemplazo", xp_unidad: 700 },
  { nombre: "Djin", xp_unidad: 7200 },
  { nombre: "Doppleganger", xp_unidad: 700 },
  { nombre: "Dragolicha", xp_unidad: 18000 },
  { nombre: "Caballo de Trabajo", xp_unidad: 50 },
  { nombre: "Tortuga Dragón", xp_unidad: 18000 },
  { nombre: "Infiltrado de la Oscuridad Soñadora", xp_unidad: 2900 },
  { nombre: "Matador Mental de la Oscuridad Soñadora", xp_unidad: 7200 },
  { nombre: "Dretch", xp_unidad: 50 },
  { nombre: "Drider", xp_unidad: 2300 },
  { nombre: "Guerrero Élite Drow de Lolth", xp_unidad: 1800 },
  { nombre: "Mago Drow de Lolth", xp_unidad: 2900 },
  { nombre: "Drow de Lolth", xp_unidad: 50 },
  { nombre: "Sacerdotisa Drow de Lolth", xp_unidad: 3900 },
  { nombre: "Druida", xp_unidad: 450 },
  { nombre: "Dríade", xp_unidad: 200 },
  { nombre: "Mephito de Polvo", xp_unidad: 100 },
  { nombre: "Águila", xp_unidad: 10 },
  { nombre: "Elemental de Tierra", xp_unidad: 1800 },
  { nombre: "Efreet", xp_unidad: 7200 },
  { nombre: "Remolino Eldritch", xp_unidad: 2300 },
  { nombre: "Cataclismo Elemental", xp_unidad: 41000 },
  { nombre: "Cultista Elemental", xp_unidad: 3900 },
  { nombre: "Elefante", xp_unidad: 1100 },
  { nombre: "Alce", xp_unidad: 50 },
  { nombre: "Comandante Garra Esmeralda", xp_unidad: 1100 },
  { nombre: "Caballero Garra Esmeralda", xp_unidad: 450 },
  { nombre: "Empíreo", xp_unidad: 50000 },
  { nombre: "Empíreo Iota", xp_unidad: 200 },
  { nombre: "Erinye", xp_unidad: 8400 },
  { nombre: "Ettercap", xp_unidad: 450 },
  { nombre: "Ettin", xp_unidad: 1100 },
  { nombre: "Dragón Feérico Adulto", xp_unidad: 450 },
  { nombre: "Dragón Feérico Joven", xp_unidad: 200 },
  { nombre: "Cultista Infernal", xp_unidad: 3900 },
  { nombre: "Icono Infernal", xp_unidad: 200 },
  { nombre: "Elemental de Fuego", xp_unidad: 1800 },
  { nombre: "Gigante de Fuego", xp_unidad: 5000 },
  { nombre: "Cráneo Flamígero", xp_unidad: 1100 },
  { nombre: "Esqueleto Llanero", xp_unidad: 700 },
  { nombre: "Gólem de Carne", xp_unidad: 1800 },
  { nombre: "Flizzlebin", xp_unidad: 200 },
  { nombre: "Flumph", xp_unidad: 25 },
  { nombre: "Hongo Espora de Gas", xp_unidad: 100 },
  { nombre: "Ghallanda Problemador", xp_unidad: 700 },
  { nombre: "Ghast", xp_unidad: 450 },
  { nombre: "Ghast Invocador de Tumbas", xp_unidad: 2300 },
  { nombre: "Fantasma", xp_unidad: 1100 },
  { nombre: "Ghoull", xp_unidad: 200 },
  { nombre: "Simio Gigante", xp_unidad: 2900 },
  { nombre: "Pico de Hacha Gigante", xp_unidad: 1800 },
  { nombre: "Tejón Gigante", xp_unidad: 50 },
  { nombre: "Murciélago Gigante", xp_unidad: 50 },
  { nombre: "Jabalí Gigante", xp_unidad: 450 },
  { nombre: "Ciempies Gigante", xp_unidad: 50 },
  { nombre: "Serpiente Gigante Estranguladora", xp_unidad: 450 },
  { nombre: "Rata Corrupta Gigante", xp_unidad: 100 },
  { nombre: "Cangrejo Gigante", xp_unidad: 25 },
  { nombre: "Cocodrilo Gigante", xp_unidad: 1800 },
  { nombre: "Águila Gigante", xp_unidad: 200 },
  { nombre: "Alce Gigante", xp_unidad: 450 },
  { nombre: "Escarabajo de Fuego Gigante", xp_unidad: 10 },
  { nombre: "Sapo Gigante", xp_unidad: 50 },
  { nombre: "Cabra Gigante", xp_unidad: 100 },
  { nombre: "Hiena Gigante", xp_unidad: 200 },
  { nombre: "Lagarto Gigante", xp_unidad: 50 },
  { nombre: "Pulpo Gigante", xp_unidad: 200 },
  { nombre: "Búho Gigante", xp_unidad: 50 },
  { nombre: "Rata Gigante", xp_unidad: 25 },
  { nombre: "Escorpión Gigante", xp_unidad: 700 },
  { nombre: "Hipocampo Gigante", xp_unidad: 100 },
  { nombre: "Tiburón Gigante", xp_unidad: 1800 },
  { nombre: "Araña Gigante", xp_unidad: 200 },
  { nombre: "Calamar Gigante", xp_unidad: 2300 },
  { nombre: "Sapo Gigante", xp_unidad: 200 },
  { nombre: "Serpiente Gigante Venenosa", xp_unidad: 50 },
  { nombre: "Buitre Gigante", xp_unidad: 200 },
  { nombre: "Avispa Gigante", xp_unidad: 100 },
  { nombre: "Garduña Gigante", xp_unidad: 25 },
  { nombre: "Araña Lobo Gigante", xp_unidad: 50 },
  { nombre: "Boca Parlante", xp_unidad: 450 },
  { nombre: "Githyanki Dracomante", xp_unidad: 15000 },
  { nombre: "Caballero Githyanki", xp_unidad: 3900 },
  { nombre: "Guerrero Githyanki", xp_unidad: 700 },
  { nombre: "Mónaco Githzerai", xp_unidad: 450 },
  { nombre: "Psión Githzerai", xp_unidad: 8400 },
  { nombre: "Zerth Githzerai", xp_unidad: 2300 },
  { nombre: "Glabrezu", xp_unidad: 5000 },
  { nombre: "Gladiador", xp_unidad: 1800 },
  { nombre: "Gnoll Demoníaco", xp_unidad: 3900 },
  { nombre: "Colmillo de Yeenoghu Gnoll", xp_unidad: 1100 },
  { nombre: "Señor de la Manada Gnoll", xp_unidad: 450 },
  { nombre: "Guerrero Gnoll", xp_unidad: 100 },
  { nombre: "Cabra", xp_unidad: 10 },
  { nombre: "Jefe Goblin", xp_unidad: 200 },
  { nombre: "Goblin Hechicero", xp_unidad: 700 },
  { nombre: "Goblin Siquis", xp_unidad: 25 },
  { nombre: "Guerrero Goblin", xp_unidad: 50 },
  { nombre: "Cría de Dragón Dorado", xp_unidad: 700 },
  { nombre: "Gorgona", xp_unidad: 1800 },
  { nombre: "Goristro", xp_unidad: 18000 },
  { nombre: "Revenant del Cementerio", xp_unidad: 2900 },
  { nombre: "Babosa Gris", xp_unidad: 100 },
  { nombre: "Slaad Gris", xp_unidad: 5000 },
  { nombre: "Cría de Dragón Verde", xp_unidad: 450 },
  { nombre: "Bruja Verde", xp_unidad: 700 },
  { nombre: "Slaad Verde", xp_unidad: 3900 },
  { nombre: "Grell", xp_unidad: 700 },
  { nombre: "Grick", xp_unidad: 450 },
  { nombre: "Grick Antiguo", xp_unidad: 2900 },
  { nombre: "Grifo", xp_unidad: 450 },
  { nombre: "Grimlock", xp_unidad: 50 },
  { nombre: "Guardia", xp_unidad: 25 },
  { nombre: "Capitán de Guardia", xp_unidad: 1100 },
  { nombre: "Naga Guardiana", xp_unidad: 5900 },
  { nombre: "Podredumbre de Gulthias", xp_unidad: 15000 },
  { nombre: "Medio‑Dragón", xp_unidad: 1800 },
  { nombre: "Harpía", xp_unidad: 200 },
  { nombre: "Demonio Recolector", xp_unidad: 700 },
  { nombre: "Revenant Haunt", xp_unidad: 5900 },
  { nombre: "Halcón", xp_unidad: 10 },
  { nombre: "Perro del Infierno", xp_unidad: 700 },
  { nombre: "Horror Encapuchado", xp_unidad: 1100 },
  { nombre: "Hezrou", xp_unidad: 3900 },
  { nombre: "Gigante de Colina", xp_unidad: 1800 },
  { nombre: "Hipogrifo", xp_unidad: 200 },
  { nombre: "Hipopótamo", xp_unidad: 1100 },
  { nombre: "Capitán Hobgoblin", xp_unidad: 700 },
  { nombre: "Señor de la Guerra Hobgoblin", xp_unidad: 2300 },
  { nombre: "Guerrero Hobgoblin", xp_unidad: 100 },
  { nombre: "Homúnculo", xp_unidad: 10 },
  { nombre: "Homúnculo Sirviente", xp_unidad: 0 },
  { nombre: "Horror Gancho", xp_unidad: 700 },
  { nombre: "Demonio Cornudo", xp_unidad: 7200 },
  { nombre: "Tiburón Depredador", xp_unidad: 450 },
  { nombre: "Hidra", xp_unidad: 3900 },
  { nombre: "Hiena", xp_unidad: 10 },
  { nombre: "Demonio de Hielo", xp_unidad: 11500 },
  { nombre: "Mephito de Hielo", xp_unidad: 100 },
  { nombre: "Diablillo", xp_unidad: 200 },
  { nombre: "Diablillo Tramposo", xp_unidad: 200 },
  { nombre: "Encarnación de la Transitoriedad", xp_unidad: 2900 },
  { nombre: "Encarnación del Brillo", xp_unidad: 5900 },
  { nombre: "Íncubo", xp_unidad: 1100 },
  { nombre: "Devorador de Inteligencias", xp_unidad: 450 },
  { nombre: "Acechador Invisible", xp_unidad: 2300 },
  { nombre: "Gólem de Hierro", xp_unidad: 15000 },
  { nombre: "Chacal", xp_unidad: 10 },
  { nombre: "Hombre‑Chacal", xp_unidad: 100 },
  { nombre: "Médico Jorasco", xp_unidad: 1100 },
  { nombre: "Dragón de las Sombras Juvénil", xp_unidad: 1100 },
  { nombre: "Karas Chembryl", xp_unidad: 3900 },
  { nombre: "Kenku", xp_unidad: 50 },
  { nombre: "Orca", xp_unidad: 700 },
  { nombre: "Caballero", xp_unidad: 700 },
  { nombre: "Guerrero Kobold", xp_unidad: 25 },
  { nombre: "Korex", xp_unidad: 450 },
  { nombre: "Kraken", xp_unidad: 50000 },
  { nombre: "Guardián Kundarak", xp_unidad: 1800 },
  { nombre: "Kuo‑Toa", xp_unidad: 50 },
  { nombre: "Kuo‑Toa Arzobispo", xp_unidad: 2300 },
  { nombre: "Kuo‑Toa Vigía", xp_unidad: 700 },
  { nombre: "Kuo‑Toa Azotador", xp_unidad: 200 },
  { nombre: "Lacedon Ghoul", xp_unidad: 200 },
  { nombre: "Lamia", xp_unidad: 1100 },
  { nombre: "Larva", xp_unidad: 10 },
  { nombre: "Lemur", xp_unidad: 25 },
  { nombre: "Lich", xp_unidad: 33000 },
  { nombre: "León", xp_unidad: 200 },
  { nombre: "Lagarto", xp_unidad: 10 },
  { nombre: "Lizardfolk Geómano", xp_unidad: 450 },
  { nombre: "Lizardfolk Soberano", xp_unidad: 1100 },
  { nombre: "Gigante Lorwyn", xp_unidad: 2300 },
  { nombre: "Escogido Lyrandar", xp_unidad: 1100 },
  { nombre: "Mago", xp_unidad: 2300 },
  { nombre: "Mago Aprendiz", xp_unidad: 450 },
  { nombre: "Mephito de Magma", xp_unidad: 100 },
  { nombre: "Magmin", xp_unidad: 100 },
  { nombre: "Mamut", xp_unidad: 2300 },
  { nombre: "Manes", xp_unidad: 25 },
  { nombre: "Manes Vapor", xp_unidad: 200 },
  { nombre: "Manshoon", xp_unidad: 10000 },
  { nombre: "Manticore", xp_unidad: 700 },
  { nombre: "Marid", xp_unidad: 7200 },
  { nombre: "Marilith", xp_unidad: 15000 },
  { nombre: "Mastín", xp_unidad: 25 },
  { nombre: "Medani Inquisitivo", xp_unidad: 700 },
  { nombre: "Medusa", xp_unidad: 2300 },
  { nombre: "Merfolk Escaramuzador", xp_unidad: 25 },
  { nombre: "Merfolk Domador de Olas", xp_unidad: 2300 },
  { nombre: "Merrow", xp_unidad: 450 },
  { nombre: "Merrow Bocabifronte", xp_unidad: 1100 },
  { nombre: "Merrow Arengador", xp_unidad: 1800 },
  { nombre: "Mezzoloth", xp_unidad: 1800 },
  { nombre: "Mimic", xp_unidad: 450 },
  { nombre: "Engendro de la Mente", xp_unidad: 2900 },
  { nombre: "Arcaño Engendro de la Mente", xp_unidad: 7200 },
  { nombre: "Minotauro de Baphomet", xp_unidad: 700 },
  { nombre: "Minotauro Esqueleto", xp_unidad: 450 },
  { nombre: "Modrón Duodrone", xp_unidad: 50 },
  { nombre: "Modrón Monodrone", xp_unidad: 25 },
  { nombre: "Modrón Pentadrone", xp_unidad: 450 },
  { nombre: "Modrón Quadrone", xp_unidad: 200 },
  { nombre: "Modrón Tridrone", xp_unidad: 100 },
  { nombre: "Mephito de Lodo", xp_unidad: 50 },
  { nombre: "Mula", xp_unidad: 25 },
  { nombre: "Momia", xp_unidad: 700 },
  { nombre: "Señor de las Momias", xp_unidad: 13000 },
  { nombre: "Myconid Adulto", xp_unidad: 100 },
  { nombre: "Myconid Soberano", xp_unidad: 450 },
  { nombre: "Myconid Sirviente de Espora", xp_unidad: 200 },
  { nombre: "Myconid Rebrote", xp_unidad: 10 },
  { nombre: "Nalfeshnee", xp_unidad: 10000 },
  { nombre: "Espina Corrompida", xp_unidad: 50 },
  { nombre: "Bruja Nocturna", xp_unidad: 1800 },
  { nombre: "Cauchemar", xp_unidad: 700 },
  { nombre: "Monte Nimblewright", xp_unidad: 450 },
  { nombre: "Nimblewright", xp_unidad: 700 },
  { nombre: "Nimblewright Hulk", xp_unidad: 2900 },
  { nombre: "Noble", xp_unidad: 25 },
  { nombre: "Noble Prodigio", xp_unidad: 5900 },
  { nombre: "Noggle Saqueador", xp_unidad: 50 },
  { nombre: "Noggle Mago Salvaje", xp_unidad: 200 },
  { nombre: "Nothic", xp_unidad: 450 },
  { nombre: "Nycaloth", xp_unidad: 5000 },
  { nombre: "Minga Ocre", xp_unidad: 450 },
  { nombre: "Pulpo", xp_unidad: 10 },
  { nombre: "Ogra", xp_unidad: 450 },
  { nombre: "Ogra Zombi", xp_unidad: 450 },
  { nombre: "Ogrillón", xp_unidad: 200 },
  { nombre: "Oni", xp_unidad: 2900 },
  { nombre: "Orien Aplastador", xp_unidad: 1100 },
  { nombre: "Otyugh", xp_unidad: 1800 },
  { nombre: "Búho", xp_unidad: 10 },
  { nombre: "Oso Búho", xp_unidad: 700 },
  { nombre: "Puma", xp_unidad: 50 },
  { nombre: "Pegaso", xp_unidad: 450 },
  { nombre: "Artista", xp_unidad: 100 },
  { nombre: "Artista Lenda", xp_unidad: 5900 },
  { nombre: "Artista Maestro", xp_unidad: 2300 },
  { nombre: "Peryton", xp_unidad: 450 },
  { nombre: "Phaerimm Agente", xp_unidad: 3900 },
  { nombre: "Phaerimm Anciano", xp_unidad: 11500 },
  { nombre: "Phaerimm Cría", xp_unidad: 50 },
  { nombre: "Phaerimm Explorador", xp_unidad: 450 },
  { nombre: "Phaerimn", xp_unidad: 50 },
  { nombre: "Phaerimn Agente", xp_unidad: 3900 },
  { nombre: "Araña de Fase", xp_unidad: 700 },
  { nombre: "Perforador", xp_unidad: 100 },
  { nombre: "Piranha", xp_unidad: 10 },
  { nombre: "Pirata", xp_unidad: 200 },
  { nombre: "Almirante Pirata", xp_unidad: 8400 },
  { nombre: "Capitán Pirata", xp_unidad: 2300 },
  { nombre: "Príncipe de las Tinieblas", xp_unidad: 25000 },
  { nombre: "Píxel", xp_unidad: 50 },
  { nombre: "Pixie Portador de Maravillas", xp_unidad: 1800 },
  { nombre: "Planetar", xp_unidad: 15000 },
  { nombre: "Plesiosaurio", xp_unidad: 450 },
  { nombre: "Oso Polar", xp_unidad: 450 },
  { nombre: "Serpiente Polar", xp_unidad: 700 },
  { nombre: "Poltergeist", xp_unidad: 450 },
  { nombre: "Pony", xp_unidad: 25 },
  { nombre: "Sacerdote", xp_unidad: 450 },
  { nombre: "Acolito Sacerdote", xp_unidad: 50 },
  { nombre: "Oso Búho Primordial", xp_unidad: 2900 },
  { nombre: "Pseudodragón", xp_unidad: 50 },
  { nombre: "Babosa Gris Psíquica", xp_unidad: 200 },
  { nombre: "Pteranodonte", xp_unidad: 50 },
  { nombre: "Gusano Púrpura", xp_unidad: 13000 },
  { nombre: "Quaggoth", xp_unidad: 450 },
  { nombre: "Quaggoth Thonot", xp_unidad: 700 },
  { nombre: "Quasit", xp_unidad: 200 },
  { nombre: "Reina Caída", xp_unidad: 5900 },
  { nombre: "Caballero Buscador", xp_unidad: 8400 },
  { nombre: "Rakshasa", xp_unidad: 10000 },
  { nombre: "Rata", xp_unidad: 10 },
  { nombre: "Cuervo", xp_unidad: 10 },
  { nombre: "Cría de Dragón Rojo", xp_unidad: 1100 },
  { nombre: "Slaad Rojo", xp_unidad: 1800 },
  { nombre: "Tiburón de Arrecife", xp_unidad: 100 },
  { nombre: "Remorhaz", xp_unidad: 7200 },
  { nombre: "Revenant", xp_unidad: 1800 },
  { nombre: "Rinoceronte", xp_unidad: 450 },
  { nombre: "Caballo de Montar", xp_unidad: 50 },
  { nombre: "Rilly June", xp_unidad: 100 },
  { nombre: "Roca", xp_unidad: 7200 },
  { nombre: "Roper", xp_unidad: 1800 },
  { nombre: "Monstruo de Óxido", xp_unidad: 100 },
  { nombre: "Behemot Oxidado", xp_unidad: 5000 },
  { nombre: "Berserker Oxidado", xp_unidad: 1100 },
  { nombre: "Wyrm Oxidado", xp_unidad: 11500 },
  { nombre: "Tigre de Dientes de Sable", xp_unidad: 450 },
  { nombre: "Sahuagin Barón", xp_unidad: 1800 },
  { nombre: "Sahuagin Sacerdote", xp_unidad: 450 },
  { nombre: "Sahuagin Guerrero", xp_unidad: 100 },
  { nombre: "Salamandra", xp_unidad: 1800 },
  { nombre: "Salamandra Serpe de Fuego", xp_unidad: 200 },
  { nombre: "Salamandra Mago del Infierno", xp_unidad: 13000 },
  { nombre: "Sammaster (Forma de Dragolicha)", xp_unidad: 41000 },
  { nombre: "Sammaster (Forma de Lich)", xp_unidad: 41000 },
  { nombre: "Sátiro", xp_unidad: 100 },
  { nombre: "Sátiro Maestro de Fiesta", xp_unidad: 2300 },
  { nombre: "Espantapájaros", xp_unidad: 200 },
  { nombre: "Escorpión", xp_unidad: 10 },
  { nombre: "Explorador", xp_unidad: 100 },
  { nombre: "Capitán Explorador", xp_unidad: 700 },
  { nombre: "Sirena Bruja", xp_unidad: 450 },
  { nombre: "Hipocampo", xp_unidad: 0 },
  { nombre: "Mariscal Guardián", xp_unidad: 2300 },
  { nombre: "Sombra", xp_unidad: 100 },
  { nombre: "Demonio de las Sombras", xp_unidad: 1100 },
  { nombre: "Dragón de la Sombra", xp_unidad: 10000 },
  { nombre: "Agente Marcado por las Sombras", xp_unidad: 2900 },
  { nombre: "Gigante Shadowmoor", xp_unidad: 3900 },
  { nombre: "Matorral Andante", xp_unidad: 1800 },
  { nombre: "Guardián del Escudo", xp_unidad: 2900 },
  { nombre: "Cría de Dragón Plateado", xp_unidad: 450 },
  { nombre: "Escriba Sivis", xp_unidad: 700 },
  { nombre: "Esqueleto", xp_unidad: 50 },
  { nombre: "Renacuajo Slaad", xp_unidad: 25 },
  { nombre: "Mephito de Humo", xp_unidad: 50 },
  { nombre: "Solar", xp_unidad: 33000 },
  { nombre: "Demonio Hablista", xp_unidad: 8400 },
  { nombre: "Espectador", xp_unidad: 700 },
  { nombre: "Espectro", xp_unidad: 200 },
  { nombre: "Esfinge de la Sabiduría", xp_unidad: 7200 },
  { nombre: "Esfinge de los Secretos", xp_unidad: 3900 },
  { nombre: "Esfinge del Valor", xp_unidad: 18000 },
  { nombre: "Esfinge de la Maravilla", xp_unidad: 200 },
  { nombre: "Araña", xp_unidad: 10 },
  { nombre: "Demonio Espinado", xp_unidad: 450 },
  { nombre: "Cría de Dragón Espiritual", xp_unidad: 450 },
  { nombre: "Naga Espiritual", xp_unidad: 3900 },
  { nombre: "Espora de Moander", xp_unidad: 8400 },
  { nombre: "Duende", xp_unidad: 50 },
  { nombre: "Espía", xp_unidad: 200 },
  { nombre: "Maestro de espías", xp_unidad: 5900 },
  { nombre: "Mephito de Vapor", xp_unidad: 50 },
  { nombre: "Defensor de Acero", xp_unidad: 0 },
  { nombre: "Murciélago Sanguijuela", xp_unidad: 25 },
  { nombre: "Gigante de Piedra", xp_unidad: 2900 },
  { nombre: "Gólem de Piedra", xp_unidad: 5900 },
  { nombre: "Gigante de Tormenta", xp_unidad: 10000 },
  { nombre: "Súcubo", xp_unidad: 1100 },
  { nombre: "Swanmay", xp_unidad: 700 },
  { nombre: "Enjambre de Murciélagos", xp_unidad: 50 },
  { nombre: "Enjambre de Ratas Corruptas", xp_unidad: 0 },
  { nombre: "Enjambre de Garras Caminantes", xp_unidad: 700 },
  { nombre: "Enjambre de Dretches", xp_unidad: 1100 },
  { nombre: "Enjambre de Insectos", xp_unidad: 100 },
  { nombre: "Enjambre de Larvas", xp_unidad: 200 },
  { nombre: "Enjambre de Lemures", xp_unidad: 700 },
  { nombre: "Enjambre de Piranhas", xp_unidad: 200 },
  { nombre: "Enjambre de Ratas", xp_unidad: 50 },
  { nombre: "Enjambre de Cuervos", xp_unidad: 50 },
  { nombre: "Enjambre de Murciélagos Sanguijuela", xp_unidad: 450 },
  { nombre: "Enjambre de Serpientes Venenosas", xp_unidad: 450 },
  { nombre: "Enjambre de Miembros Zombi (DMR)", xp_unidad: 200 },
  { nombre: "Tarkanan Merodeador", xp_unidad: 7200 },
  { nombre: "Tarkanan Matón", xp_unidad: 200 },
  { nombre: "Tarrasque", xp_unidad: 155000 },
  { nombre: "Terran Magen", xp_unidad: 3900 },
  { nombre: "Cazador Tharashk", xp_unidad: 2300 },
  { nombre: "Thri‑kreen Merodeador", xp_unidad: 200 },
  { nombre: "Thri‑kreen Psión", xp_unidad: 3900 },
  { nombre: "Tigre", xp_unidad: 200 },
  { nombre: "Tufón", xp_unidad: 100 },
  { nombre: "Tufón Jefe", xp_unidad: 1100 },
  { nombre: "Treant", xp_unidad: 5000 },
  { nombre: "Corrupción de Árbol", xp_unidad: 2900 },
  { nombre: "Triceratopo", xp_unidad: 1800 },
  { nombre: "Troglodita", xp_unidad: 50 },
  { nombre: "Troll", xp_unidad: 1800 },
  { nombre: "Miembro de Troll", xp_unidad: 100 },
  { nombre: "Corrupción de Vara", xp_unidad: 25 },
  { nombre: "Tiranosaurio Rex", xp_unidad: 3900 },
  { nombre: "Ultroloth", xp_unidad: 10000 },
  { nombre: "Umber Hulk", xp_unidad: 1800 },
  { nombre: "Umbragen Andador de Sombras", xp_unidad: 5000 },
  { nombre: "Unicornio", xp_unidad: 1800 },
  { nombre: "Heredero Vadalis", xp_unidad: 1100 },
  { nombre: "Valindra Capa de Sombras", xp_unidad: 33000 },
  { nombre: "Vampiro", xp_unidad: 10000 },
  { nombre: "Vampiro Familiar", xp_unidad: 700 },
  { nombre: "Vampiro Infernal", xp_unidad: 11500 },
  { nombre: "Vampiro Portador de la Noche", xp_unidad: 3900 },
  { nombre: "Engendro Vampírico", xp_unidad: 1800 },
  { nombre: "Vampiro Señor de las Sombras", xp_unidad: 13000 },
  { nombre: "Vampiro Guardián", xp_unidad: 5900 },
  { nombre: "Serpiente Venenosa", xp_unidad: 25 },
  { nombre: "Corrupción de Liana", xp_unidad: 100 },
  { nombre: "Tangler Corrupto de Liana", xp_unidad: 0 },
  { nombre: "Fungo Violeta", xp_unidad: 50 },
  { nombre: "Violet Fungus Necrohulk", xp_unidad: 2900 },
  { nombre: "Vircos Magen", xp_unidad: 2300 },
  { nombre: "Vrock", xp_unidad: 2300 },
  { nombre: "Vulkoori Cuchilla de Aguijón", xp_unidad: 100 },
  { nombre: "Vulkoori Sacerdote de Veneno", xp_unidad: 450 },
  { nombre: "Buitre", xp_unidad: 10 },
  { nombre: "Caballo de Guerra", xp_unidad: 100 },
  { nombre: "Caballo de Guerra Esqueleto", xp_unidad: 100 },
  { nombre: "Comandante Guerrero", xp_unidad: 5900 },
  { nombre: "Infantería Guerrero", xp_unidad: 25 },
  { nombre: "Guerrero Veterano", xp_unidad: 700 },
  { nombre: "Elemental de Agua", xp_unidad: 1800 },
  { nombre: "Entidad de Agua", xp_unidad: 700 },
  { nombre: "Garduña", xp_unidad: 10 },
  { nombre: "Oso Hombre", xp_unidad: 1800 },
  { nombre: "Jabalí Hombre", xp_unidad: 1100 },
  { nombre: "Rata Hombre", xp_unidad: 450 },
  { nombre: "Tigre Hombre", xp_unidad: 1100 },
  { nombre: "Hombre Lobo", xp_unidad: 700 },
  { nombre: "Wyvern Hombre", xp_unidad: 3900 },
  { nombre: "Cría de Dragón Blanco", xp_unidad: 450 },
  { nombre: "Wight", xp_unidad: 700 },
  { nombre: "Luz Fugaz", xp_unidad: 450 },
  { nombre: "Kobold Alado", xp_unidad: 50 },
  { nombre: "Lobo de Invierno", xp_unidad: 700 },
  { nombre: "Lobo", xp_unidad: 50 },
  { nombre: "Worg", xp_unidad: 100 },
  { nombre: "Wraith", xp_unidad: 1800 },
  { nombre: "Wyvern", xp_unidad: 2300 },
  { nombre: "Xorn", xp_unidad: 1800 },
  { nombre: "Yeti", xp_unidad: 700 },
  { nombre: "Yochlol", xp_unidad: 5900 },
  { nombre: "Dragón Negro Joven", xp_unidad: 2900 },
  { nombre: "Dragón Azul Joven", xp_unidad: 5000 },
  { nombre: "Dragón de Latón Joven", xp_unidad: 2300 },
  { nombre: "Dragón de Bronce Joven", xp_unidad: 3900 },
  { nombre: "Dragón de Cobre Joven", xp_unidad: 2900 },
  { nombre: "Dragón Profundo Joven", xp_unidad: 1800 },
  { nombre: "Dragón Dorado Joven", xp_unidad: 5900 },
  { nombre: "Dragón Verde Joven", xp_unidad: 3900 },
  { nombre: "Dragón Rojo Joven", xp_unidad: 5900 },
  { nombre: "Remorhaz Joven", xp_unidad: 1800 },
  { nombre: "Dragón Plateado Joven", xp_unidad: 5000 },
  { nombre: "Dragón Espiritual Joven", xp_unidad: 3900 },
  { nombre: "Dragón Blanco Joven", xp_unidad: 2300 },
  { nombre: "Abominación Yuan‑Ti", xp_unidad: 2900 },
  { nombre: "Infiltrado Yuan‑Ti", xp_unidad: 200 },
  { nombre: "Yuan‑ti Malison (Tipo 1)", xp_unidad: 700 },
  { nombre: "Yuan‑ti Malison (Tipo 2)", xp_unidad: 700 },
  { nombre: "Yuan‑ti Malison (Tipo 3)", xp_unidad: 700 },
  { nombre: "Paladin Zhentilar de Bane", xp_unidad: 1100 },
  { nombre: "Soldado Zhentilar", xp_unidad: 200 },
  { nombre: "Zlan", xp_unidad: 20000 },
  { nombre: "Zombi", xp_unidad: 50 },
  { nombre: "Coágulo Zombi (DMR)", xp_unidad: 2300 },
];